import test,{before,beforeEach,after} from 'node:test';import assert from 'node:assert/strict';import {build} from 'esbuild';import {ObjectId} from 'mongodb';import {writeFile,unlink} from 'node:fs/promises';import {fileURLToPath} from 'node:url';
let docs,discovery;const out=fileURLToPath(new URL(`../node_modules/.cache/discovery-${process.pid}.mjs`,import.meta.url));
const match=(doc,query)=>Object.entries(query).every(([k,v])=>k==='$or'?v.some(q=>match(doc,q)):v?.$in?v.$in.some(id=>String(id)===String(doc[k])):v?.$gt?doc[k]>v.$gt:v===null?doc[k]==null:String(doc[k])===String(v));
before(async()=>{const b=await build({entryPoints:[fileURLToPath(new URL('../lib/discovery.mjs',import.meta.url))],bundle:true,write:false,platform:'node',format:'esm',external:['react','mongodb'],plugins:[{name:'db-fixture',setup(b){b.onResolve({filter:/^server-only$/},()=>({path:'empty',namespace:'test'}));b.onResolve({filter:/db\.mjs$/},()=>({path:'db',namespace:'test'}));b.onLoad({filter:/.*/,namespace:'test'},({path})=>({contents:path==='empty'?'':'export async function db(){return globalThis.__discoveryDb}'}));}}]});await writeFile(out,b.outputFiles[0].contents);discovery=await import(out);});
beforeEach(()=>{docs={subjects:[],resources:[],news:[]};globalThis.__discoveryDb={collection(name){return {async findOne(q){return docs[name].find(d=>match(d,q))||null;},find(q){let list=docs[name].filter(d=>match(d,q));const c={sort(){return c;},limit(n){list=list.slice(0,n);return c;},async toArray(){return list;}};return c;}};}};});
after(async()=>{await unlink(out);delete globalThis.__discoveryDb;});
test('Discovery applies publication and active-course gates, including malformed IDs',async()=>{const sid=new ObjectId(),rid=new ObjectId();docs.subjects=[{_id:sid,name:'Course',active:true}];docs.resources=[{_id:rid,subjectId:sid,title:'Published',status:'draft'}];assert.equal(await discovery.readEntry('resources',String(rid)),null);docs.resources[0].status='published';assert.equal((await discovery.readEntry('resources',String(rid))).title,'Published');docs.subjects[0].active=false;assert.equal(await discovery.readEntry('resources',String(rid)),null);assert.equal(await discovery.readEntry('resources','$where'),null);});
test('Discovery projections exclude infrastructure, upload bytes and private account fields',async()=>{const sid=new ObjectId(),rid=new ObjectId();docs.subjects=[{_id:sid,active:true}];docs.resources=[{_id:rid,subjectId:sid,status:'published',title:'x',adminEmail:'private',passwordHash:'secret',upload:{filename:'file.pdf',bytes:10,data:'PRIVATE BINARY'}}];const r=await discovery.readEntry('resources',String(rid));assert.deepEqual(r.upload,{filename:'file.pdf',bytes:10});assert.doesNotMatch(JSON.stringify(r),/PRIVATE|private|passwordHash|adminEmail/);});
test('Expired and unpublished announcements are not indexable public entries',async()=>{const id=new ObjectId();docs.news=[{_id:id,status:'published',title:'x',expiresAt:new Date(Date.now()-1000)}];assert.equal(await discovery.readEntry('news',String(id)),null);docs.news[0].expiresAt=null;assert.equal((await discovery.readEntry('news',String(id))).title,'x');docs.news[0].status='archived';assert.equal(await discovery.readEntry('news',String(id)),null);});
