'use client';
import {useEffect,useState} from 'react';
import {api,Icon,Notice,Empty,Field,Modal} from './shared';
const duration=ms=>!ms?'٠ د':`${(ms/60000).toLocaleString('ar-EG',{maximumFractionDigits:1})} د`;
const num=n=>Number(n||0).toLocaleString('ar-EG');
export function AnalyticsDashboard() {
  const [data,setData]=useState(null),[campaigns,setCampaigns]=useState([]),[days,setDays]=useState('30'),[error,setError]=useState(''),[loading,setLoading]=useState(true);
  useEffect(()=>{
    let alive=true,pending=false;
    const load=async()=>{if(pending)return;pending=true;try{const [stats,ads]=await Promise.all([api(`admin/analytics?days=${days}`),api('admin/campaigns')]);if(alive){setData(stats);setCampaigns(ads.campaigns);setError('');}}catch(e){if(alive)setError(e.message);}finally{pending=false;if(alive)setLoading(false);}};
    setLoading(true);load();const timer=setInterval(()=>{if(document.visibilityState==='visible')load();},30000);
    return()=>{alive=false;clearInterval(timer);};
  },[days]);
  const adRows=campaigns.map(c=>{const impressions=data?.ads.find(r=>r._id.target===c._id&&r._id.type==='ad_impression')?.sessions||0,clicks=data?.ads.find(r=>r._id.target===c._id&&r._id.type==='ad_click')?.sessions||0;return {...c,impressions,clicks};});
  const labels={home:'الرئيسية',subjects:'المواد',library:'المكتبة',news:'الإعلانات',saved:'المحفوظات',sources:'المصادر'};
  const series = [];
  if (data?.daily.length) {
    const rows = new Map(data.daily.map(d=>[d.day,d]));
    for(let day=new Date(`${data.from}T12:00:00Z`); day.toISOString().slice(0,10)<=data.today.day; day.setUTCDate(day.getUTCDate()+1)) {
      const key=day.toISOString().slice(0,10); series.push(rows.get(key)||{day:key,devices:0,sessions:0,foregroundMs:0,activeMs:0});
    }
  }
  const max=Math.max(1,...series.map(d=>d.devices));
  const points=series.map((d,i)=>`${20+i*(660/Math.max(1,series.length-1))},${180-150*d.devices/max}`).join(' ');
  return <div className="insights-page"><div className="insights-toolbar"><p>صورة واقعية للنشاط المقاس، بتوقيت القاهرة.</p><select aria-label="فترة الإحصائيات" value={days} onChange={e=>setDays(e.target.value)}><option value="7">آخر ٧ أيام</option><option value="30">آخر ٣٠ يومًا</option></select></div><Notice error>{error}</Notice>{!data?<Empty title={loading?'جاري قراءة النشاط':'الإحصائيات غير متاحة'}/>:<>
    <div className="stats-grid insight-stats">{[
      ['متصفحات نشطة اليوم',num(data.today.devices),'user'],['متصلون الآن',num(data.onlineDevices),'eye'],['حسابات الطلبة',num(data.registered),'graduate'],['جلسات اليوم',num(data.today.sessions),'chart'],['متوسط التصفح',duration(data.totals.sessions?data.totals.foregroundMs/data.totals.sessions:0),'clock'],['متوسط النشاط',duration(data.totals.sessions?data.totals.activeMs/data.totals.sessions:0),'check'],['متوسط جلسة المتصلين',duration(data.avgOnlineMs),'clock'],['وقت الدراسة النشط',duration(data.totals.activeMs),'book']
    ].map(([label,count,icon])=><div className="stat-card" key={label}><span>{label}<Icon name={icon} size={19}/></span><strong>{count}</strong></div>)}</div>
    <section className="panel activity-chart"><div className="section-heading"><div><p className="eyebrow">النشاط اليومي</p><h2>متصفحات رجعت للمنصة</h2></div><span className="tag">Africa/Cairo</span></div>{data.daily.length?<><svg viewBox="0 0 700 210" role="img" aria-label="رسم يوضح عدد المتصفحات النشطة المقاسة يوميًا"><path d="M20 180h660M20 105h660M20 30h660" className="chart-grid"/><polyline points={points} className="chart-line"/>{series.map((d,i)=><circle key={d.day} cx={20+i*(660/Math.max(1,series.length-1))} cy={180-150*d.devices/max} r="4" className="chart-point"><title>{d.day}: {d.devices} متصفح</title></circle>)}</svg><div className="chart-range"><span>{data.from}</span><span>{data.today.day}</span></div><details><summary>عرض الأرقام اليومية</summary><div className="table-scroll"><table><thead><tr><th>اليوم</th><th>المتصفحات</th><th>جلسات</th><th>وقت التصفح</th><th>وقت النشاط</th></tr></thead><tbody>{data.daily.map(d=><tr key={d.day}><td>{d.day}</td><td>{num(d.devices)}</td><td>{num(d.sessions)}</td><td>{duration(d.foregroundMs)}</td><td>{duration(d.activeMs)}</td></tr>)}</tbody></table></div></details></>:<Empty title="لسه مفيش نشاط مقاس">الأرقام هتظهر بعد موافقة أول زائر على القياس. مفيش بيانات افتراضية.</Empty>}</section>
    <div className="insights-columns"><section className="panel"><h2>أقسام بيزورها الطلبة</h2>{data.views.length?data.views.map(v=><div className="insight-row" key={v._id}><span>{labels[v._id]||v._id}</span><strong>{num(v.sessions)} جلسة</strong></div>):<p className="muted">لم يُسجّل نشاط أقسام بعد.</p>}</section><section className="panel"><h2>إزاي بنحسب؟</h2><p className="muted">التصفح: وقت التبويب الظاهر. النشاط: وقت التفاعل في التبويب الظاهر مع مهلة خمول ٦٠ ثانية. متصل الآن: نبضة ظاهرة خلال ٤٥ ثانية.</p><p className="muted">المتوسطات حسب جلسات الأيام في الفترة المختارة. المتصفحات ليست أشخاصًا مؤكدين، والقياس اختياري وتقديري، وليس مناسبًا للفوترة أو اتخاذ قرارات هوية.</p><p className="muted">آخر تحديث: {new Date(data.generatedAt).toLocaleTimeString('ar-EG',{timeZone:'Africa/Cairo'})}</p></section></div>
    <section className="panel"><h2>أداء الإعلانات</h2>{adRows.length?<div className="table-scroll"><table><thead><tr><th>الحملة</th><th>ظهور في جلسات</th><th>جلسات ضغطت</th><th>نسبة الضغط</th></tr></thead><tbody>{adRows.map(c=><tr key={c._id}><td>{c.title}</td><td>{num(c.impressions)}</td><td>{num(c.clicks)}</td><td>{c.impressions?`${(100*c.clicks/c.impressions).toLocaleString('ar-EG',{maximumFractionDigits:1})}%`:'—'}</td></tr>)}</tbody></table></div>:<p className="muted">أضف حملة من قسم الإعلانات الممولة.</p>}<p className="account-note">نعدّ الظهور والضغط مرة واحدة لكل حملة في جلسة اليوم، للزوار الموافقين على القياس فقط.</p></section>
  </>}</div>;
}
function localDate(value){const d=new Date(value);return new Date(d.valueOf()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);}
const defaults=()=>({title:'',description:'',label:'اعرف أكتر',url:'',slot:'home',status:'draft',startsAt:localDate(Date.now()),endsAt:''});
export function CampaignManager() {
  const [campaigns,setCampaigns]=useState([]),[editing,setEditing]=useState(null),[form,setForm]=useState(defaults),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false),[archive,setArchive]=useState(null);
  async function load(){const r=await api('admin/campaigns');setCampaigns(r.campaigns);setLoaded(true);}
  useEffect(()=>{load().catch(e=>setError(e.message));},[]);
  function edit(item){setEditing(item?._id||'new');setForm(item?{...item,startsAt:localDate(item.startsAt),endsAt:item.endsAt?localDate(item.endsAt):''}:defaults());setError('');}
  async function save(e){e.preventDefault();if(busy)return;setBusy(true);setError('');try{const b={...form,startsAt:new Date(form.startsAt).toISOString(),endsAt:form.endsAt?new Date(form.endsAt).toISOString():''};await api(`admin/campaigns${editing==='new'?'':`/${editing}`}`,{method:editing==='new'?'POST':'PUT',body:JSON.stringify(b)});setEditing(null);await load();setMessage('اتحفظت الحملة. موعد النشر ومكانها بيتطبقوا تلقائيًا.');}catch(e){setError(e.message);}finally{setBusy(false);}}
  return <><Notice error>{error}</Notice><Notice>{message}</Notice><section className="panel"><div className="section-heading"><div><h2>إعلانات هادية، في مكانها</h2><p className="muted">بطاقة واحدة في الرئيسية أو الفوتر. بدون نوافذ إجبارية أو سكربتات تتبّع خارجية.</p></div><button onClick={()=>edit(null)}><Icon name="plus" size={18}/>حملة جديدة</button></div>{!loaded?<Empty title="جاري تحميل الحملات"/>:campaigns.length?campaigns.map(c=><div className="campaign-row" key={c._id}><span className="shortcut-icon"><Icon name="megaphone"/></span><div className="row-copy"><strong>{c.title}</strong><p>{new URL(c.url).hostname} · {c.slot==='home'?'الرئيسية':'الفوتر'}</p></div><span className="tag">{{draft:'مسودة',published:'منشور / مجدول',archived:'مؤرشف'}[c.status]}</span><div className="row-actions"><button className="secondary small" onClick={()=>edit(c)}>تعديل</button>{c.status!=='archived'&&<button className="danger small" onClick={()=>setArchive(c)}>أرشفة</button>}</div></div>):<Empty title="ابدأ بأول حملة">الإعلانات المنشورة تظهر للطلبة في مواعيدها، وأداءها يظهر في الإحصائيات.</Empty>}</section>
    {editing&&<Modal title={editing==='new'?'حملة إعلانية جديدة':'تعديل الحملة'} onClose={()=>setEditing(null)}><Notice error>{error}</Notice><form onSubmit={save}><div className="form-grid"><Field label="عنوان الحملة"><input required maxLength={120} value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></Field><Field label="نص الزر"><input required maxLength={40} value={form.label} onChange={e=>setForm({...form,label:e.target.value})}/></Field><Field label="رابط الإعلان"><input required type="url" dir="ltr" placeholder="https://" value={form.url} onChange={e=>setForm({...form,url:e.target.value})}/></Field><Field label="مكان الإعلان"><select value={form.slot} onChange={e=>setForm({...form,slot:e.target.value})}><option value="home">الرئيسية</option><option value="footer">الفوتر</option></select></Field><Field label="بداية الحملة"><input required type="datetime-local" value={form.startsAt} onChange={e=>setForm({...form,startsAt:e.target.value})}/></Field><Field label="نهاية الحملة (اختياري)"><input type="datetime-local" value={form.endsAt} onChange={e=>setForm({...form,endsAt:e.target.value})}/></Field></div><Field label="وصف مختصر"><textarea maxLength={250} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></Field><Field label="حالة النشر"><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="draft">مسودة</option><option value="published">منشور / مجدول</option><option value="archived">مؤرشف</option></select></Field><p className="account-note">المواعيد بتوقيت جهازك. عند وجود أكثر من حملة سارية في نفس المكان، تظهر أحدث حملة فقط.</p><button disabled={busy}>{busy?'جاري الحفظ…':'حفظ الحملة'}</button></form></Modal>}
    {archive&&<Modal title="أرشفة الإعلان" onClose={()=>setArchive(null)}><p>إيقاف «{archive.title}»؟ يمكنك استرجاعه من تعديل الحملة.</p><button disabled={busy} className="danger" onClick={async()=>{setBusy(true);try{await api(`admin/campaigns/${archive._id}`,{method:'DELETE',body:'{}'});setArchive(null);await load();}catch(e){setError(e.message);}finally{setBusy(false);}}}>أرشفة الحملة</button></Modal>}
  </>;
}
export function StudentDirectory() {
  const [data,setData]=useState(null),[error,setError]=useState(''),[q,setQ]=useState('');
  useEffect(()=>{api('admin/students').then(setData).catch(e=>setError(e.message));},[]);
  const students=data?.students.filter(s=>`${s.name} ${s.email}`.toLowerCase().includes(q.toLowerCase()))||[];
  const names=new Map((data?.students||[]).map(s=>[s._id,`${s.name} · ${s.email}`]));
  return <><Notice error>{error}</Notice><section className="panel"><div className="section-heading"><div><h2>حسابات الطلبة</h2><p className="muted">آخر ٢٠٠ حساب. عرض للمالك فقط، بدون كلمات مرور أو رموز جلسات.</p></div><span className="tag">مالك المنصة</span></div><label className="search-box"><Icon name="search"/><input aria-label="بحث في حسابات الطلبة" placeholder="اسم أو بريد المعهد…" value={q} onChange={e=>setQ(e.target.value)}/></label>{!data?<Empty title="جاري تحميل الحسابات"/>:students.length?<div className="table-scroll"><table><thead><tr><th>الاسم</th><th>البريد</th><th>التحقق</th><th>تاريخ الانضمام</th></tr></thead><tbody>{students.map(s=><tr key={s._id}><td>{s.name}</td><td dir="ltr">{s.email}</td><td>{s.emailVerified?'موثّق':'غير موثّق'}</td><td>{new Date(s.createdAt).toLocaleDateString('ar-EG')}</td></tr>)}</tbody></table></div>:<p className="muted">لا توجد حسابات مطابقة.</p>}</section><section className="panel"><h2>حسابات على متصفح مشترك</h2><p className="muted">نستخدم معرّفًا عشوائيًا لنفس المتصفح، وليس بصمة إلكترونية خفية. قد يكون الجهاز مشتركًا بين أشخاص مختلفين. لا تعتمد على الإشارة وحدها للحظر أو إثبات الهوية.</p>{data?.sharedBrowsers.length?data.sharedBrowsers.map(b=><div className="browser-group" key={b.label}><h3><Icon name="shield" size={18}/>{b.label}</h3><ul>{b.studentIds.map(id=><li key={id}>{names.get(id)||'حساب خارج آخر ٢٠٠ حساب'}</li>)}</ul><small>آخر دخول: {new Date(b.lastSeenAt).toLocaleString('ar-EG')}</small></div>):<p className="muted">لم تُرصد حسابات متعددة على نفس المتصفح.</p>}</section></>;
}
