'use client';
import {useEffect,useState} from 'react';
import {api,Field,Icon,Notice,Modal,Empty} from './shared';
import CreativeFields from './CreativeFields';
import {creativeSrc} from '../lib/ad-selection.mjs';
const defaults=()=>({business:'',contact:'',title:'',description:'',url:'',label:'اعرف أكتر',slot:'home',icon:null,banner:null,notes:'',acceptReview:false});
const labels={pending:'بانتظار المراجعة',approved:'مقبول · تجهيز حملة',rejected:'يحتاج تعديل'};
export function AdvertiseDialog({user,onClose,onSignIn}){
 const [form,setForm]=useState(defaults),[rows,setRows]=useState([]),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const change=(key,value)=>setForm(s=>({...s,[key]:value}));
 async function load(){const r=await api('student/ad-requests');setRows(r.requests);}
 useEffect(()=>{if(user)load().catch(e=>setError(e.message));},[user?._id]);
 async function submit(e){e.preventDefault();if(busy||uploading)return;setBusy(true);setError('');try{await api('student/ad-requests',{method:'POST',body:JSON.stringify(form)});setForm(defaults());setMessage('اترسل طلبك للمراجعة. الموافقة لا تعني النشر الفوري أو بدء أي رسوم.');await load();}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <Modal title="حط إعلانك على EIA" onClose={onClose}><p className="account-note">وصل رسالتك للطلبة في بطاقة واضحة. فريق المنصة يراجع المحتوى ويتواصل معك بشأن التفاصيل قبل نشر الحملة. لا توجد مدفوعات تلقائية.</p><Notice error>{error}</Notice><Notice>{message}</Notice>{!user?<div className="advertise-intro"><Icon name="megaphone" size={34}/><h3>ابدأ من حسابك</h3><p>سجّل دخول حساب الطالب لتقديم طلب إعلان ومتابعة مراجعته. تفاصيل التواصل تظهر لفريق المراجعة فقط.</p><button onClick={onSignIn}>تسجيل دخول الطالب</button></div>:<><form onSubmit={submit}><div className="form-grid"><Field label="اسم المشروع أو النشاط"><input required maxLength={100} value={form.business} onChange={e=>change('business',e.target.value)}/></Field><Field label="وسيلة التواصل للمراجعة"><input required maxLength={150} placeholder="هاتف أو بريد للتواصل" value={form.contact} onChange={e=>change('contact',e.target.value)}/></Field><Field label="عنوان الإعلان"><input required maxLength={120} value={form.title} onChange={e=>change('title',e.target.value)}/></Field><Field label="رابط الوجهة"><input required type="url" dir="ltr" value={form.url} onChange={e=>change('url',e.target.value)}/></Field><Field label="نص الزر"><input required maxLength={40} value={form.label} onChange={e=>change('label',e.target.value)}/></Field><Field label="المكان المطلوب"><select value={form.slot} onChange={e=>change('slot',e.target.value)}><option value="home">الرئيسية</option><option value="footer">الفوتر</option></select></Field></div><Field label="وصف مختصر"><textarea maxLength={250} value={form.description} onChange={e=>change('description',e.target.value)}/></Field><CreativeFields value={form} onChange={change} onBusy={setUploading}/><Field label="ملاحظات للفريق"><textarea maxLength={600} value={form.notes} onChange={e=>change('notes',e.target.value)}/></Field><label className="checkline"><input required type="checkbox" checked={form.acceptReview} onChange={e=>change('acceptReview',e.target.checked)}/>أوافق على مشاركة تفاصيل هذا الطلب ووسيلة التواصل مع فريق مراجعة الإعلانات.</label><button disabled={busy||uploading}><Icon name="send" size={17}/>{busy?'جاري إرسال الطلب…':'إرسال للمراجعة'}</button></form><section className="ad-request-history"><h3>طلباتك الأخيرة</h3>{rows.length?rows.map(row=><article className="ad-request-item" key={row._id}><div><strong>{row.title}</strong><span className="tag">{labels[row.status]}</span></div><p>{row.reviewReason||'التفاصيل محفوظة في طلبك.'}</p><button className="text-button small" onClick={()=>{setForm({...defaults(),...row,acceptReview:false});setMessage('عدّل التفاصيل وأرسل طلبًا جديدًا للمراجعة. الطلب السابق والحملة الحالية لا يتغيّران.');}}>نسخة معدّلة للمراجعة</button></article>):<p className="muted">لم تقدّم طلبًا بعد.</p>}</section></>}</Modal>;
}
export function AdReviewQueue(){
 const [rows,setRows]=useState([]),[loaded,setLoaded]=useState(false),[filter,setFilter]=useState('pending'),[review,setReview]=useState(null),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 async function load(){const r=await api('admin/ad-requests');setRows(r.requests);setLoaded(true);}
 useEffect(()=>{load().catch(e=>setError(e.message));},[]);
 async function decide(action){setBusy(true);setError('');try{await api(`admin/ad-requests/${review._id}`,{method:'PUT',body:JSON.stringify({action,version:review.version,reason})});setReview(null);setMessage(action==='approve'?'اتقبل الطلب واتجهّزت حملة مسودة. افتح الإعلانات الممولة لمراجعة التوزيع وموعد النشر.':'اتحفظت ملاحظات المراجعة لصاحب الطلب.');await load();}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <><Notice error>{error}</Notice><Notice>{message}</Notice><section className="panel"><div className="section-heading"><div><h2>طلبات المعلنين</h2><p className="muted">الموافقة تجهّز حملة مسودة؛ النشر والتوزيع من قسم الإعلانات الممولة.</p></div><select aria-label="حالة طلبات الإعلانات" value={filter} onChange={e=>setFilter(e.target.value)}><option value="pending">بانتظار المراجعة</option><option value="approved">مقبول</option><option value="rejected">يحتاج تعديل</option><option value="">الكل</option></select></div>{!loaded?<Empty title="جاري قراءة الطلبات"/>:rows.filter(r=>!filter||r.status===filter).map(row=><article className="campaign-row" key={row._id}><span className="shortcut-icon"><Icon name="megaphone"/></span><div className="row-copy"><strong>{row.title}</strong><p>{row.business} · {row.applicantName}</p></div><span className="tag">{labels[row.status]}</span><button className="secondary small" onClick={()=>{setReview(row);setReason(row.reviewReason||'');}}>عرض الطلب</button></article>)}{loaded&&!rows.some(r=>!filter||r.status===filter)&&<Empty title="مفيش طلبات في الحالة دي"/>}</section>{review&&<Modal title="مراجعة طلب الإعلان" onClose={()=>setReview(null)}><Notice error>{error}</Notice><div className="review-contact"><strong>{review.business}</strong><p>{review.applicantName} · {review.applicantEmail}</p><p>التواصل: {review.contact}</p><p>المكان المطلوب: {review.slot==='home'?'الرئيسية':'الفوتر'}</p></div>{review.banner&&<img className="creative-preview banner" src={creativeSrc(review.banner,'admin')} alt="البانر المطلوب" width="480" height="180" referrerPolicy="no-referrer"/>}{review.icon&&<img className="creative-preview icon" src={creativeSrc(review.icon,'admin')} alt="الأيقونة المطلوبة" width="80" height="80" referrerPolicy="no-referrer"/>}<h3>{review.title}</h3><p>{review.description}</p><a className="text-button" href={review.url} target="_blank" rel="noopener noreferrer">فتح الوجهة الخارجية</a><p className="account-note">ملاحظات المعلن: {review.notes||'لا توجد ملاحظات.'}</p><Field label="ملاحظات المراجعة لصاحب الطلب"><textarea maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></Field><div className="form-actions">{review.status==='pending'&&<><button disabled={busy} onClick={()=>decide('approve')}>قبول وتجهيز مسودة</button><button className="secondary" disabled={busy} onClick={()=>decide('reject')}>إرجاع بملاحظات</button></>}{review.status==='approved'&&<button disabled={busy} className="secondary" onClick={()=>decide('approve')}>تأكيد تجهيز الحملة</button>}</div></Modal>}</>;
}
