'use client';
import {useState} from 'react';
import {api,Field,Icon,Notice} from './shared';
import {creativeSrc} from '../lib/ad-selection.mjs';
export default function CreativeFields({value,onChange,area='student',onBusy}) {
 const [busy,setBusy]=useState(''),[error,setError]=useState('');
 async function upload(kind,file){if(!file)return;if(file.size>1024*1024){setError('الصورة بحد أقصى ١ ميجابايت.');return;}setBusy(kind);onBusy?.(true);setError('');try{const body=new FormData();body.set('file',file);body.set('kind',kind);const r=await api(`${area}/ad-media`,{method:'POST',body});onChange(kind,r.image);}catch(e){setError(e.message);}finally{setBusy('');onBusy?.(false);}}
 return <div className="creative-fields"><Notice error>{error}</Notice>{['icon','banner'].map(kind=><section className="creative-field" key={kind}><div><h3>{kind==='icon'?'أيقونة الإعلان':'بانر الإعلان'}</h3><p>{kind==='icon'?'صورة مربعة · ١٦٠ × ١٦٠':'صورة عريضة · ٩٦٠ × ٣٦٠'}</p></div>{value[kind]&&<img src={creativeSrc(value[kind],area)} width={kind==='icon'?80:480} height={kind==='icon'?80:180} alt={kind==='icon'?'معاينة الأيقونة':'معاينة البانر'} referrerPolicy="no-referrer" className={`creative-preview ${kind}`}/>}<Field label={kind==='icon'?'رابط الأيقونة المباشر':'رابط البانر المباشر'}><input type="url" dir="ltr" placeholder="https://example.com/image.webp" value={value[kind]?.kind==='url'?value[kind].url:''} onChange={e=>onChange(kind,e.target.value?{kind:'url',url:e.target.value}:null)}/></Field><label className="creative-upload"><Icon name="upload" size={17}/>{busy===kind?'جاري تجهيز الصورة…':'أو ارفع صورة من جهازك'}<input type="file" aria-label={kind==='icon'?'رفع أيقونة الإعلان':'رفع بانر الإعلان'} accept="image/png,image/jpeg,image/webp" disabled={Boolean(busy)} onChange={e=>void upload(kind,e.target.files?.[0])}/></label>{value[kind]&&<button className="text-button small" type="button" disabled={Boolean(busy)} onClick={()=>onChange(kind,null)}>إزالة الصورة من الطلب</button>}</section>)}<p className="account-note">الرفع متاح لصور PNG وJPEG وWebP، بحد أقصى ١ ميجابايت للصورة. الصورة تُضغط وتُزال بياناتها الوصفية. الرابط المباشر يحمّل الصورة من مزوده.</p></div>;
}
