'use client';
import {useEffect,useState} from 'react';
import {api,Modal,Field,Notice,Icon} from './shared';
import {PrivacyPanel} from './Telemetry';
import PwaTools from './PwaTools';
export default function StudentAccount({metrics,user,onClose,onChanged,onAuthBusy,cloudStatus,emailVerificationAvailable}) {
  const [mode,setMode]=useState('login'),[section,setSection]=useState('account'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
  const [form,setForm]=useState({name:'',email:'',password:'',acceptPrivacy:false}),[plan,setPlan]=useState({items:[],version:0}),[task,setTask]=useState({title:'',date:''}),[passwords,setPasswords]=useState({currentPassword:'',password:''}),[code,setCode]=useState(''),[verification,setVerification]=useState(Boolean(emailVerificationAvailable));
  const [personal,setPersonal]=useState({name:user?.name||'',phone:'',studentCode:'',city:'',bio:''});
  useEffect(()=>{if(user)setPersonal({name:user.name,...user.personal});},[user?.name,user?.profileVersion,user?._id]);
  async function act(action){if(busy)return;setBusy(true);setError('');setMessage('');try{await action();return true;}catch(e){setError(e.message);return false;}finally{setBusy(false);}}
  async function refresh(){const snapshot=await api('student/session');setVerification(snapshot.emailVerificationAvailable);onChanged(snapshot);}

  useEffect(()=>{if(user&&section==='plan')void act(async()=>setPlan(await api('student/planner')));},[user?._id,section]);
  async function authenticate(event){event.preventDefault();onAuthBusy(true);try{await act(async()=>{await api(`student/${mode}`,{method:'POST',body:JSON.stringify(form)});setForm({name:'',email:'',password:'',acceptPrivacy:false});await refresh();setSection('preferences');setMessage('أهلًا بيك. اختار إعدادات الإشعارات والخصوصية؛ تقدر تعدّلها هنا في أي وقت.');});}finally{onAuthBusy(false);}}
  async function savePlan(items){return await act(async()=>{setPlan(await api('student/planner',{method:'PUT',body:JSON.stringify({items,version:plan.version})}));setMessage('اتحفظت خطتك.');});}
  return <Modal title={user?'مساحتك الشخصية':'حساب الطالب'} onClose={onClose}><Notice error>{error}</Notice><Notice>{message}</Notice>{!user?<>
    <div className="account-intro"><span className="account-emblem"><Icon name="graduate" size={30}/></span><h3>{mode==='register'?'ابدأ بحسابك الدراسي':'أهلًا بعودتك'}</h3><p>محفوظاتك، تقدمك وخطة مذاكرتك، متزامنين بين أجهزتك.</p></div>
    <div className="segmented-control"><button type="button" className={mode==='login'?'active':''} onClick={()=>{setMode('login');setError('');}}>تسجيل الدخول</button><button type="button" className={mode==='register'?'active':''} onClick={()=>{setMode('register');setError('');}}>إنشاء حساب</button></div>
    <form onSubmit={authenticate} className="student-auth-form">{mode==='register'&&<Field label="اسمك"><input required maxLength={100} autoComplete="name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field>}<Field label="بريد المعهد"><input required type="email" dir="ltr" autoComplete="username" placeholder="bis.2410423@eia.edu.eg" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></Field><Field label="كلمة المرور"><input required type="password" minLength={mode==='register'?12:1} maxLength={128} autoComplete={mode==='register'?'new-password':'current-password'} value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></Field>
    {mode==='register'&&<><p className="account-note">اختار كلمة مرور خاصة بالمنصة؛ لا تستخدم كلمة مرور بريد المعهد. إنشاء الحساب لا يثبت ملكية البريد، ولا يمنح أي صلاحيات إدارة.</p><label className="checkline"><input type="checkbox" required checked={form.acceptPrivacy} onChange={e=>setForm({...form,acceptPrivacy:e.target.checked})}/>أوافق على حفظ بيانات حسابي ومعرّف متصفح عشوائي لأمان الدخول وربط الحسابات على نفس المتصفح. قياس النشاط اختياري بشكل مستقل.</label></>}
    <button className="full" disabled={busy}>{busy?'لحظة…':mode==='register'?'إنشاء حساب الطالب':'دخول حساب الطالب'}<Icon name="arrow" size={18}/></button></form><p className="account-note">{verification?'تقدر توثّق ملكية بريدك بكود من داخل حسابك.':'إرسال أكواد التحقق لسه غير متاح. الحساب بيظهر كبريد غير موثّق.'}</p>
  </>:<>
    <div className="student-identity"><span className="avatar">{user.name[0]}</span><div><h3>{user.name}</h3><p dir="ltr">{user.email}</p></div><span className={`tag ${user.emailVerified?'mint':''}`}>{user.emailVerified?'بريد موثّق':'بريد غير موثّق'}</span></div>
    <div className="segmented-control"><button className={section==='account'?'active':''} onClick={()=>setSection('account')}>حسابي</button><button className={section==='plan'?'active':''} onClick={()=>setSection('plan')}>خطة الدراسة</button><button className={['preferences','security'].includes(section)?'active':''} onClick={()=>setSection('preferences')}>الإعدادات</button></div>
    <div className="account-section" key={section}>
    {section==='account'&&<><form className="personal-profile-form" onSubmit={e=>{e.preventDefault();void act(async()=>{await api('student/profile',{method:'PUT',body:JSON.stringify({...personal,version:user.profileVersion||0})});await refresh();setMessage('اتحفظ البروفايل. الهاتف وكود الطالب بيانات خاصة وغير موثّقة.');});}}><h3>بياناتك الشخصية</h3><div className="form-grid"><Field label="الاسم"><input required maxLength={100} autoComplete="name" value={personal.name} onChange={e=>setPersonal({...personal,name:e.target.value})}/></Field><Field label="رقم الهاتف (اختياري)"><input type="tel" dir="ltr" maxLength={20} autoComplete="tel" value={personal.phone||''} onChange={e=>setPersonal({...personal,phone:e.target.value})}/></Field><Field label="كود الطالب (اختياري)"><input dir="ltr" maxLength={24} value={personal.studentCode||''} onChange={e=>setPersonal({...personal,studentCode:e.target.value})}/></Field><Field label="المدينة (اختياري)"><input maxLength={80} autoComplete="address-level2" value={personal.city||''} onChange={e=>setPersonal({...personal,city:e.target.value})}/></Field></div><Field label="نبذة عنك (اختياري)"><textarea maxLength={300} value={personal.bio||''} onChange={e=>setPersonal({...personal,bio:e.target.value})}/></Field><p className="account-note">التفاصيل خاصة بحسابك، ولا تظهر في الإعلانات أو الإحصائيات العامة. كود الطالب والهاتف لا يثبتان الهوية أو القيد بالمعهد.</p><button disabled={busy}>حفظ البروفايل</button></form><section className="account-feature"><Icon name="cloud"/><div><h3>مكتبتك معاك، على كل جهاز</h3><p>{cloudStatus==='error'?'المزامنة متوقفة. حدّث الحساب لاسترجاع النسخة المحفوظة.':cloudStatus==='pending'?'جاري مزامنة تقدمك ومحفوظاتك…':'مسارك، محفوظاتك وتقدمك متزامنين مع حسابك.'}</p></div></section><button className="secondary" disabled={busy} onClick={()=>act(refresh)}><Icon name="refresh" size={17}/>إعادة تحميل بيانات الحساب</button>{!user.emailVerified&&<section className="verification-card"><h3>تأكيد ملكية البريد</h3><p>{verification?'أرسل كودًا إلى بريدك، ثم اكتبه هنا.':'لا توجد خدمة بريد متصلة حاليًا؛ لن نعرض حسابك كحساب موثّق.'}</p>{verification&&<><button className="secondary small" disabled={busy} onClick={()=>act(async()=>{await api('student/verification',{method:'POST',body:'{}'});setMessage('لو الإرسال نجح، هتلاقي الكود في بريدك.');})}>إرسال كود التحقق</button><form onSubmit={e=>{e.preventDefault();void act(async()=>{await api('student/verification',{method:'POST',body:JSON.stringify({code})});setCode('');await refresh();setMessage('اتأكدنا من ملكية البريد.');});}}><Field label="كود التحقق"><input required dir="ltr" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} autoComplete="one-time-code" value={code} onChange={e=>setCode(e.target.value)}/></Field><button disabled={busy}>تأكيد البريد</button></form></>}</section>}</>}
    {section==='plan'&&<><div className="planner-summary"><Icon name="calendar"/><span>{plan.items.filter(i=>i.done).length} من {plan.items.length} مهمة مكتملة</span><button className="text-button small" disabled={busy} onClick={()=>act(async()=>setPlan(await api('student/planner')))}>تحديث</button></div><form className="planner-form" onSubmit={e=>{e.preventDefault();if(!task.title.trim())return;void savePlan([...plan.items,{id:crypto.randomUUID(),title:task.title,date:task.date,done:false}]).then(ok=>{if(ok)setTask({title:'',date:''});});}}><Field label="مهمة الدراسة"><input required maxLength={150} placeholder="مثلًا: مذاكرة المحاضرة الثالثة" value={task.title} onChange={e=>setTask({...task,title:e.target.value})}/></Field><Field label="الموعد (اختياري)"><input type="date" value={task.date} onChange={e=>setTask({...task,date:e.target.value})}/></Field><button disabled={busy||plan.items.length>=60}><Icon name="plus" size={18}/>إضافة مهمة</button></form><div className="planner-list">{[...plan.items].sort((a,b)=>Number(a.done)-Number(b.done)||(a.date||'9999').localeCompare(b.date||'9999')).map(item=><div key={item.id} className={`planner-item ${item.done?'done':''}`}><label><input type="checkbox" checked={item.done} disabled={busy} onChange={()=>savePlan(plan.items.map(i=>i.id===item.id?{...i,done:!i.done}:i))}/><span><strong>{item.title}</strong>{item.date&&<small>{item.date}</small>}</span></label><button className="icon-button secondary" disabled={busy} aria-label={`حذف ${item.title}`} onClick={()=>savePlan(plan.items.filter(i=>i.id!==item.id))}><Icon name="trash" size={18}/></button></div>)}{!plan.items.length&&<p className="muted">ابدأ بمهمة صغيرة. خطتك خاصة بحسابك.</p>}</div></>}
    {section==='preferences'&&<><div className="settings-intro"><h3>الخصوصية والإشعارات</h3><p>القياس اختياري. اختيارك محفوظ على حسابك، والإشعارات تُدار لكل جهاز حسب إذن المتصفح.</p></div>{metrics&&<PrivacyPanel metrics={metrics}/>}<PwaTools compact/><button className="secondary account-security-entry" onClick={()=>setSection('security')}><Icon name="shield" size={18}/>كلمة المرور وأمان الحساب</button></>}
    {section==='security'&&<><p className="account-note">تغيير كلمة المرور ينهي جلساتك الأخرى، ويعيد تأمين جلستك الحالية.</p><form onSubmit={e=>{e.preventDefault();void act(async()=>{await api('student/password',{method:'POST',body:JSON.stringify(passwords)});setPasswords({currentPassword:'',password:''});setMessage('اتغيّرت كلمة المرور واتقفلت الجلسات الأخرى.');});}}><Field label="كلمة المرور الحالية"><input type="password" required autoComplete="current-password" value={passwords.currentPassword} onChange={e=>setPasswords({...passwords,currentPassword:e.target.value})}/></Field><Field label="كلمة مرور جديدة"><input type="password" required minLength={12} maxLength={128} autoComplete="new-password" value={passwords.password} onChange={e=>setPasswords({...passwords,password:e.target.value})}/></Field><button disabled={busy}>تغيير كلمة المرور</button></form><p className="account-note">معرّف المتصفح قد يجمع حسابات لأشخاص مختلفين على جهاز مشترك. ده مؤشر للأمان، مش إثبات إنهم نفس الشخص.</p></>}
    </div><div className="account-bottom"><span className="muted">حساب طالب · بدون صلاحيات إدارة</span><button className="text-button" disabled={busy} onClick={()=>{onAuthBusy(true);void act(async()=>{await api('student/logout',{method:'POST',body:'{}'});onChanged({user:null,state:null});onClose();}).finally(()=>onAuthBusy(false));}}><Icon name="logout" size={17}/>تسجيل الخروج</button></div>
  </>}</Modal>;
}
